-- begin QUERYDSL_CUBA_ANIMAL
alter table QUERYDSL_CUBA_ANIMAL add constraint FK_QUERYDSL_CUBA_ANIMAL_ON_CAT foreign key (CAT_ID) references QUERYDSL_CUBA_ANIMAL(ID);
create unique index IDX_QUERYDSL_CUBA_ANIMAL_UK_INT_ID on QUERYDSL_CUBA_ANIMAL (INT_ID) where DELETE_TS is null;
create index IDX_QUERYDSL_CUBA_ANIMAL_ON_CAT on QUERYDSL_CUBA_ANIMAL (CAT_ID);
-- end QUERYDSL_CUBA_ANIMAL
